---
- name: This is a demo play
  hosts: localhost
  become: true
  tasks:
    - name: This is a name filler
      copy:
        content: |
          Lets make a change
        dest: /home/testfile.txt
    - name: This is a plugin example
      debug:
        msg: "{{ lookup('file', '/home/testfile.txt') }}"
